kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: kernel
  image: ubuntu:bionic
  commands:
#  - cat /proc/cpuinfo
  - apt-get update
  - apt-get install -y curl
  - curl -o vagrant.deb https://releases.hashicorp.com/vagrant/2.2.2/vagrant_2.2.2_x86_64.deb
  - curl -o virtualbox.deb https://download.virtualbox.org/virtualbox/6.0.0/virtualbox-6.0_6.0.0-127566~Ubuntu~bionic_amd64.deb
  - dpkg -i virtualbox.deb
  - dpkg -i vagrant.deb
