kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: kernel
  image: ubuntu:bionic
  commands:
#  - cat /proc/cpuinfo
  - apt-get update
  - apt-get install -y curl
  - echo "deb https://download.virtualbox.org/virtualbox/debian bionic contrib" >> /etc/apt/sources.list
  - curl -o oracle_vbox_2016.asc https://www.virtualbox.org/download/oracle_vbox_2016.asc
  - apt-key add oracle_vbox_2016.asc
  - apt-get update
  - apt-get install -y virtualbox-6.0
  - curl -o vagrant.deb https://releases.hashicorp.com/vagrant/2.2.2/vagrant_2.2.2_x86_64.deb
  - dpkg -i virtualbox.deb
