kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: kernel
  image: ubuntu:bionic
  commands:
#  - cat /proc/cpuinfo
  - apt-get update
  - apt-get install -y curl gnupg
  - curl -o vagrant.deb https://releases.hashicorp.com/vagrant/2.2.2/vagrant_2.2.2_x86_64.deb
  - dpkg -i vagrant.deb
  - vagrant up  
