kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: kernel
  image: ubuntu:xenial
  commands:
  - cat /proc/cpuinfo
  - wget https://releases.hashicorp.com/vagrant/2.2.2/vagrant_2.2.2_x86_64.deb -O vagrant.deb
  - wget https://download.virtualbox.org/virtualbox/6.0.0/virtualbox-6.0_6.0.0-127566~Ubuntu~bionic_amd64.deb -O virtualbox.deb
  - dpkg -i virtualbox.deb
  - dpkg -i vagrant.deb
